[build]
  command = "npm run build"
  publish = "dist/"
  [build.processing]
    skip_processing = true
  [build.environment]
    CI = "1" # https://www.voorhoede.nl/en/blog/10x-faster-nuxt-builds-on-netlify/#skip-streaming-logs
    NPM_CONFIG_AUDIT = "false"

[context.preview]
  environment = { APP_PREVIEW = "true" }

[dev]
  dir = "dist/"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
