[build]
  command = "npm run build"
  publish = "dist/"
  [build.processing]
    skip_processing = true

[context.preview]
  environment = { APP_PREVIEW = "true" }

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
