[build]
  command = "npm run build::production"
  publish = "dist/"
  [context.preview]
    command = "npm run build::preview"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
